<a href="https://colab.research.google.com/github/Stephane-Masamba/Team_4_CPT_ML-Classification/blob/Rachel/Draft.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Introduction

####Problem Statement : Build a model that classifies whether or not a person believes in climate change based on their novel tweet data



###Import Libraries

In [0]:
import spacy
import re
nlp =spacy.load('en_core_web_sm')

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

##Importing the dataset

In [0]:
train= pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

###EDA

In [135]:
train.head()

sentiment                                            message  tweetid
0          1  PolySciMajor EPA chief doesn't think carbon di...   625221
1          1  It's not like we lack evidence of anthropogeni...   126103
2          2  RT @RawStory: Researchers say we have three ye...   698562
3          1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736
4          1  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   466954

In [136]:
test.head()

message  tweetid
0  Europe will now be looking to China to make su...   169760
1  Combine this with the polling of staffers re c...    35326
2  The scary, unimpeachable evidence that climate...   224985
3  @Karoli @morgfair @OsborneInk @dailykos \nPuti...   476263
4  RT @FakeWillMoore: 'Female orgasms cause globa...   872928

In [137]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15819 entries, 0 to 15818
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   sentiment  15819 non-null  int64 
 1   message    15819 non-null  object
 2   tweetid    15819 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 370.9+ KB


In [138]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10546 entries, 0 to 10545
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   message  10546 non-null  object
 1   tweetid  10546 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 164.9+ KB


In [0]:
"Mikael Daniel's Wisdom code block"

i = 0
for tweet in train['message']:
  tweet = tweet.lower()
  tweet = re.sub(r'http\S+', 'LINK', tweet)
  tweet = re.sub(r'@\S+', 'USER_REF', tweet)
  tweet = re.sub(r'[^\w\s]', '', tweet)
  tweet = tweet.lstrip()
  tweet = tweet.rstrip()
  train.loc[i, 'message'] = tweet
  i += 1

In [140]:
train.head()

sentiment                                            message  tweetid
0          1  polyscimajor epa chief doesnt think carbon dio...   625221
1          1  its not like we lack evidence of anthropogenic...   126103
2          2  rt USER_REF researchers say we have three year...   698562
3          1  todayinmaker wired  2016 was a pivotal year in...   573736
4          1  rt USER_REF its 2016 and a racist sexist clima...   466954

In [0]:
#nlp.Defaults.stop_words.add('LINK')
#nlp.Defaults.stop_words.add('USER_REF')


##Modeling

In [0]:
#train_data = train.drop('sentiment', axis=1)
train_data = train['message']
target = train['sentiment']

In [142]:
train_data.head()

0    polyscimajor epa chief doesnt think carbon dio...
1    its not like we lack evidence of anthropogenic...
2    rt USER_REF researchers say we have three year...
3    todayinmaker wired  2016 was a pivotal year in...
4    rt USER_REF its 2016 and a racist sexist clima...
Name: message, dtype: object

In [143]:
target.head()

0    1
1    1
2    2
3    1
4    1
Name: sentiment, dtype: int64

###Libraries

In [0]:
# Importing Classifier Modules
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

Splitting the DATA


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train_data, target, test_size = 0.2, random_state = 42)

In [0]:
#Mikael Dinael's WISDOM

from sklearn.feature_extraction.text import TfidfVectorizer
tf_vect = TfidfVectorizer()
X_train = tf_vect.fit_transform(X_train)
X_test =tf_vect.transform(X_test)

In [147]:
print(X_train)

  (0, 8281)	0.06957591816835199
  (0, 2542)	0.05487590994863743
  (0, 2865)	0.05390170792219766
  (0, 13440)	0.24149615939992125
  (0, 13863)	0.08569672304302682
  (0, 13563)	0.3386088171641152
  (0, 7335)	0.3609626185772794
  (0, 12808)	0.39644903932413356
  (0, 6614)	0.4267812578023314
  (0, 4871)	0.39644903932413356
  (0, 864)	0.4267812578023314
  (1, 5691)	0.11510256055449578
  (1, 11507)	0.31614051960668055
  (1, 13660)	0.0734310417549819
  (1, 13013)	0.3627346641782572
  (1, 10602)	0.3028746709817802
  (1, 4930)	0.3067933556988044
  (1, 12853)	0.2770943751456248
  (1, 236)	0.2673362335207203
  (1, 8116)	0.258468987303189
  (1, 1345)	0.30552593038733905
  (1, 4735)	0.3067933556988044
  (1, 9169)	0.2877941646601316
  (1, 7541)	0.08944181835697725
  (1, 13828)	0.22843341526768735
  :	:
  (12652, 13863)	0.20540835060874738
  (12653, 4478)	0.43934870435159334
  (12653, 12472)	0.39995503746463124
  (12653, 2719)	0.39995503746463124
  (12653, 3076)	0.39348557670500706
  (12653, 5176)	0.

In [148]:
print(y_train)

6735     1
13537    2
6876     1
10035    2
5174     0
        ..
13418    1
5390     1
860      1
15795    2
7270     1
Name: sentiment, Length: 12655, dtype: int64


In [149]:
print(X_test)

  (0, 15365)	0.1560669583401975
  (0, 15333)	0.22572088338283733
  (0, 14993)	0.18581310758531305
  (0, 14521)	0.056690078140356724
  (0, 13742)	0.37344579586736176
  (0, 13731)	0.21059753980597645
  (0, 13627)	0.3371257382528513
  (0, 11855)	0.06547096380025641
  (0, 9869)	0.20923157732638462
  (0, 8455)	0.36757910471219346
  (0, 8281)	0.06985380690993609
  (0, 7597)	0.17252098451137524
  (0, 7541)	0.10565450794381355
  (0, 7195)	0.11124321829606135
  (0, 5618)	0.28795238764450354
  (0, 5169)	0.38822867692437285
  (0, 4321)	0.1937708055478612
  (0, 2865)	0.054116993299352004
  (0, 2542)	0.055095086324032295
  (0, 1488)	0.26641521108700417
  (1, 14622)	0.17664667307088033
  (1, 14313)	0.25953827175174304
  (1, 13835)	0.2602349451782772
  (1, 12504)	0.3974670765232267
  (1, 9801)	0.11444530241828299
  :	:
  (3162, 14872)	0.24580832666457167
  (3162, 14521)	0.05411629598445988
  (3162, 11855)	0.062498521286748744
  (3162, 8180)	0.2559227199028337
  (3162, 7558)	0.2055368954382886
  (3162

###Classification Techniques

##Logistic

In [150]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter=1000)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred = classifier.predict(X_test)

In [152]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  84   33  149   12]
 [   9  165  227   24]
 [   8   56 1561  130]
 [   3    4  160  539]]


0.7424146649810367

In [153]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred_random, average='macro')

0.2411206440188389

Cross validation

In [0]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
k_fold = KFold(n_splits=10, shuffle=True, random_state=0)

###Decision Tree

In [155]:
clf = DecisionTreeClassifier()
scoring = 'accuracy'
score = cross_val_score(clf, X_train, y_train, cv=k_fold, n_jobs=1, scoring=scoring)
print(score)
# decision tree Score
np.mean(score)

[0.6121643  0.59557662 0.59873618 0.59557662 0.60900474 0.61106719
 0.61976285 0.62766798 0.61897233 0.59130435]


0.6079833155374057

##KNN

In [156]:
clf = KNeighborsClassifier(n_neighbors = 7)
scoring = 'accuracy'
score = cross_val_score(clf, X_train, y_train, cv=k_fold, n_jobs=1, scoring=scoring)
print(score)
# kNN Score
np.mean(score)

[0.63507109 0.65323855 0.63665087 0.64849921 0.67061611 0.64664032
 0.66007905 0.65059289 0.66956522 0.65849802]


0.6529451323455032

In [157]:
from sklearn.neighbors import KNeighborsClassifier
random_classifier = KNeighborsClassifier(n_neighbors = 7, metric = 'minkowski', p = 2)
random_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [0]:
y_pred_random = random_classifier.predict(X_test)

In [159]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_random)
print(cm)
accuracy_score(y_test, y_pred_random)

[[  91   55  106   26]
 [  22  184  180   39]
 [  40  152 1332  231]
 [   6   37  188  475]]


0.6580278128950695

In [128]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred_random, average='macro')

0.5420915299855646

###Random Forest

In [160]:
clf = RandomForestClassifier(n_estimators=7)
scoring = 'accuracy'
score = cross_val_score(clf, X_train, y_train, cv=k_fold, n_jobs=1, scoring=scoring)
print(score)
# Random Forest Score
np.mean(score)

[0.66982622 0.65086888 0.66982622 0.67219589 0.69115324 0.65928854
 0.67588933 0.69328063 0.66719368 0.67588933]


0.6725411960112145

In [161]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 7, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=7,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [169]:
#normal score
normal_score =classifier.score(X_train,y_train)
normal_score

0.9795337811141841

In [0]:
#cross validation score after fitting model
scoring_new = 'accuracy'
new_score = cross_val_score(classifier, X_train, y_train, cv=k_fold, n_jobs=1, scoring=scoring_new)




In [0]:
print(new_score)
# Random Forest Score
np.mean(new_score)

[0.671406   0.66666667 0.68562401 0.68483412 0.68878357 0.67272727
 0.66324111 0.68932806 0.67747036 0.65928854]


0.675936971195574

In [0]:
#Finding confusion matrix and the accuracy_score
y_predict = classifier.predict(X_test)

In [168]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_predict)
print(cm)
accuracy_score(y_test, y_predict)

[[  66   43  160    9]
 [  19  140  246   20]
 [  28  103 1446  178]
 [   6   13  217  470]]


0.6706700379266751

In [131]:
#Macro F1-score
from sklearn.metrics import f1_score
f1_score(y_test, y_predict, average='macro')

0.5217825995049584

###Bayes

In [98]:
clf = GaussianNB()
scoring = 'accuracy'
score = cross_val_score(clf, X_train, y_train, cv=k_fold, n_jobs=1, scoring=scoring)
print(score)
# Naive Bayes Score
np.mean(score)

[nan nan nan nan nan nan nan nan nan nan]


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
TypeError: A sparse matrix was passed, but dense data is required. Use X.toarray() to convert to a dense numpy array.

  FitFailedWarning)


nan

###SVM

In [100]:
clf = SVC()
scoring = 'accuracy'
score = cross_val_score(clf, X_train, y_train, cv=k_fold, n_jobs=1, scoring=scoring)
print(score)
#the score
np.mean(score)

[0.72985782 0.7235387  0.71484992 0.72274882 0.72511848 0.72964427
 0.7312253  0.72252964 0.73517787 0.73280632]


0.7267497143285315

In [110]:
from sklearn.svm import SVC
svm_classifier = SVC(kernel = 'linear', random_state = 0)
svm_classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [115]:
score = svm_classifier.score(X_train,y_train)
score

0.8911892532595812

In [0]:
y_pred = svm_classifier.predict(X_test)

In [114]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  86   32  132    9]
 [  17  169  253   32]
 [  18   60 1502  126]
 [   6    9  164  549]]


0.7288242730720607

In [116]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred, average='macro')

0.6154245364319182

###Kernel SVM